-- Séparation « Description du poste » (mission/rôle) et « Description des tâches » (champ existant
-- `description`), pour un affichage à deux colonnes façon Factorial sur le contrat.
ALTER TABLE "public"."FichePoste" ADD COLUMN IF NOT EXISTS "descriptionPoste" TEXT;

-- Réécriture en prose (façon Factorial) du contenu existant « Chef de salle ».
-- Guardé (descriptionPoste NULL) → ne s'exécute qu'une fois, sans écraser d'édition ultérieure.
UPDATE "public"."FichePoste"
SET "descriptionPoste" = $desc$Le chef de salle est responsable du bon déroulement du service en salle chez Pâtes en Folie. Rattaché à la gérante, il pilote l'équipe de salle, garantit la qualité de l'accueil et du service, et assure la liaison permanente entre la salle et la cuisine. Il veille au respect des standards de la maison, à la satisfaction des clients et à la bonne tenue des encaissements, tout en formant et en encadrant son équipe.$desc$,
    "description" = $tache$Avant chaque service, le chef de salle organise et supervise la mise en place (tables, couverts, verres, nappes, carte et ménagère), répartit les rangs et les missions au sein de l'équipe, et informe celle-ci des réservations, des menus du jour et des consignes de la gérante. Pendant le service, il accueille et installe les clients, supervise le déroulement du service, veille au rythme des envois (commandes, plats, desserts, additions) en lien étroit avec la cuisine et intervient immédiatement en cas de litige ou d'insatisfaction. Après le service, il supervise le nettoyage et le rangement de la salle, vérifie les encaissements et remet le rapport de caisse à la gérante, puis recense les manquants en stock à transmettre à la direction.

Au quotidien, il fait respecter les standards de service définis par la direction, traite les réclamations avec diplomatie et efficacité, contrôle les stocks de matériel de salle (linge, vaisselle, couverts) et signale les manques, et supervise la conformité de la facturation et des encaissements. Il forme et accompagne les nouveaux membres et stagiaires, évalue les performances et remonte les besoins en formation à la direction. Il tient enfin compte des contraintes propres à l'établissement : horaires décalés et coupures midi/soir organisés dans le respect des 36 h/semaine, station debout prolongée nécessitant des pauses régulières, gestion du stress en période de rush, forte chaleur du climat de Kinshasa (salle climatisée ou ventilée, hydratation régulière) et coupures d'électricité fréquentes couvertes par un groupe électrogène de secours.$tache$
WHERE TRIM("poste") ILIKE 'chef de salle' AND ("descriptionPoste" IS NULL OR "descriptionPoste" = '');
