// Liste figée des légumes frais (reprise de la feuille « Légumes frais » de l'inventaire).
export const LEGUMES: { nom: string; unite: string }[] = [
  { nom: "Ail", unite: "Kg" },
  { nom: "Ananas", unite: "Pièce" },
  { nom: "Aubergine", unite: "Kg" },
  { nom: "Basilic", unite: "Botte" },
  { nom: "Carottes", unite: "Kg" },
  { nom: "Céléri", unite: "Pièce" },
  { nom: "Ciboulettes", unite: "Bottes" },
  { nom: "Citron jaune", unite: "Kg" },
  { nom: "Citron local", unite: "Kg" },
  { nom: "Concombre", unite: "Kg" },
  { nom: "Courgettes", unite: "Kg" },
  { nom: "Épinard", unite: "Kg" },
  { nom: "Feuilles de Laurier", unite: "Kg" },
  { nom: "Gingembre", unite: "Kg" },
  { nom: "Haricot vert", unite: "Kg" },
  { nom: "Jus de Citron", unite: "Unité" },
  { nom: "Lemons / Citrons-verts", unite: "Kg" },
  { nom: "Mangue", unite: "Pièce" },
  { nom: "Maracuja", unite: "Pièce" },
  { nom: "Oignons", unite: "Kg" },
  { nom: "Orange", unite: "Kg" },
  { nom: "Pastèque", unite: "Pièce" },
  { nom: "Persil", unite: "Botte" },
  { nom: "Piments", unite: "Ekolo" },
  { nom: "Poireaux", unite: "Kg" },
  { nom: "Poivron Jaune et rouge", unite: "Kg" },
  { nom: "Poivron vert", unite: "Kg" },
  { nom: "Pomme", unite: "Kg" },
  { nom: "Pommes de terre", unite: "Kg" },
  { nom: "Salade Lolo", unite: "Kg" },
  { nom: "Thym", unite: "Botte" },
  { nom: "Tomates fraiches", unite: "Kg" },
  { nom: "Tomates cerises", unite: "Kg" },
  { nom: "Feuilles de menthe", unite: "Botte" },
];
